### ISSUE TITLE
Hello, I have some questions about your article "FedSpace".

### ISSUE THREAD

**Issue by dmndxld** [jinhyun-so/Multi-roundSecAgg#1]
FedSpace is very groundbreaking work on satellites and this work is very solid. We've been investigating this work recently and we're very interested in it.  We have benefited greatly after reading your dissertation. We would like to follow your work. Is your FedSpace framework open source, or is it convenient to provide us with a copy? Thank you very much.

**Comment by jinhyun-so** [comment]
Thanks for your interests on FedSpace. Unfortunately, it is work during my Internship at MSR, and it cannot be on the public due to the confidential issue.

**Comment by dmndxld** [comment]
ok, still thanks for your help.

> Thanks for your interests on FedSpace. Unfortunately, it is work during my Internship at MSR, and it cannot be on the public due to the confidential issue.

ok, still thanks for your help.
